<?php
/**
 * @package Lightweight_Columns
 * @version 1.1
 */
/*
Plugin Name: Lightweight Columns
Plugin URI: http://github.com/kangabell/lightweight-columns
Description: Shortcodes for simple, responsive columns. Includes thirds, halves, and three-column flowing text.
Author: Kay Belardinelli
Version: 1.1
Author URI: http://kangabell.co
*/


/* LOAD STYLESHEET */
add_action( 'wp_enqueue_scripts', 'lwc_scripts');

/* ADD GALLERY SHORTCODE */
add_shortcode( 'fbg', 'flexbox_gallery' );

/* REMOVE PARAGRAPH TAGS GENERATED BY WORDPRESS */
remove_filter('the_content', 'wpautop');


/*** FUNCTIONS ***/

function lwc_scripts() {
    wp_enqueue_style( 'lwc-css', plugins_url( 'style.css', __FILE__ ) );
}

function flexbox_gallery( $atts, $content = null ) {
    return "<div class='fbg'>" . do_shortcode($content) . "</div>";
}
    

?>